# 前回のおさらい

ライブラリを使うときには

import ライブラリ名 as 別名

- 単独要素の抽出

　名前での抽出 df.at[行名,列名]

　番号での抽出 df.iat[行番号,列番号]

- **特定範囲の抽出**

　名前での抽出 df.loc[(start)行名:(end)行名,(start)列名:(end)列名]

　番号での抽出 df.iloc[(start)行番号:(end)行番号,(start)列番号:(end)列番号

# JupyterNotebookのつかいかたまとめました！
https://qiita.com/kobayu0902art/items/ca231dfb0ab8e3a4f06f

# 今回は...

# 6.要素に対する操作
  - ### 6-2.要素の削除
  
# 4.挿入
  - ### 4-1.行の挿入
  - ### 4-2.列の挿入

# 5.行のソート

# これでPandasは最低限使えるように

# Pandas操作を条件分岐・ループで扱う

 - if
 - switch case
 - while
 - for
 - 例外処理
 - 上記の組み合わせ
 
# +変数のはなし

In [1]:
import pandas as pd
df = pd.read_csv("PokemonStatus_Gen8.csv")
df = df.set_index("ポケモン名" , drop = False)
df.head()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309

## 行の抽出

前回のlocを応用して

In [2]:
df.loc["ピカチュウ",:]

図鑑番号        25
ポケモン名    ピカチュウ
タイプ１       でんき
タイプ２       NaN
通常特性１    せいでんき
通常特性２      NaN
夢特性      ひらいしん
HP          35
こうげき        55
ぼうぎょ        40
とくこう        50
とくぼう        50
すばやさ        90
合計         320
Name: ピカチュウ, dtype: object

In [41]:
type(df)

pandas.core.frame.DataFrame

In [3]:
type(df.loc["ピカチュウ",:])

pandas.core.series.Series

In [4]:
pd.DataFrame(df.loc["ピカチュウ",:])

       ピカチュウ
図鑑番号      25
ポケモン名  ピカチュウ
タイプ１     でんき
タイプ２     NaN
通常特性１  せいでんき
通常特性２    NaN
夢特性    ひらいしん
HP        35
こうげき      55
ぼうぎょ      40
とくこう      50
とくぼう      50
すばやさ      90
合計       320

In [42]:
type(pd.DataFrame(df.loc["ピカチュウ",:]))

pandas.core.frame.DataFrame

In [5]:
pd.DataFrame(df.loc["ピカチュウ",:]).T

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ピカチュウ,25,ピカチュウ,でんき,NaN,せいでんき,NaN,ひらいしん,35,55,40,50,50,90,320

# Transpose(転置)

In [6]:
Pikachu = pd.DataFrame(df.loc["ピカチュウ",:]).T

行の抽出ができた

## 行の抽出

**df.loc[行名,:]**

# 破壊的メソッドと非破壊的メソッド

In [43]:
df

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ブリザポス,896,ブリザポス,こおり,NaN,しろのいななき,NaN,NaN,100,145,130,65,110,30,580
レイスポス,897,レイスポス,ゴースト,NaN,くろのいななき,NaN,NaN,100,65,60,145,80,130,580
バドレックス,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500
バドレックス(はくばじょうのすがた),898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680
バドレックス(こくばじょうのすがた),898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680

In [47]:
df_aaa = df
df_aaa.at["ピカチュウ","ポケモン名"] = "no name"
pd.DataFrame(df_aaa.loc["ピカチュウ",:]).T

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
no name,25,no name,でんき,NaN,せいでんき,NaN,ひらいしん,35,55,40,50,50,90,320

In [49]:
Pikachu.loc

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ピカチュウ,25,ピカチュウ,でんき,NaN,せいでんき,NaN,ひらいしん,35,55,40,50,50,90,320

# 6-2.要素の削除

## DataFrameの行を指定して削除
- 行名（行ラベル）で指定
- 行番号で指定

## DataFrameの列を指定して削除
- 列名（列ラベル）で指定
- 列番号で指定

In [7]:
df.head()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309

In [8]:
df.drop("フシギバナ")

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309
リザード,5,リザード,ほのお,NaN,もうか,NaN,サンパワー,58,64,58,80,65,80,405
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ブリザポス,896,ブリザポス,こおり,NaN,しろのいななき,NaN,NaN,100,145,130,65,110,30,580
レイスポス,897,レイスポス,ゴースト,NaN,くろのいななき,NaN,NaN,100,65,60,145,80,130,580
バドレックス,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500
バドレックス(はくばじょうのすがた),898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680
バドレックス(こくばじょうのすがた),898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680

In [10]:
df.drop(["フシギバナ","リザードン","カメックス"]).head(15)

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309
リザード,5,リザード,ほのお,NaN,もうか,NaN,サンパワー,58,64,58,80,65,80,405
メガリザードンX,6,メガリザードンX,ほのお,ドラゴン,かたいツメ,NaN,NaN,78,130,111,130,85,100,634
メガリザードンY,6,メガリザードンY,ほのお,ひこう,ひでり,NaN,NaN,78,104,78,159,115,100,634
ゼニガメ,7,ゼニガメ,みず,NaN,げきりゅう,NaN,あめうけざら,44,48,65,50,64,43,314
カメール,8,カメール,みず,NaN,げきりゅう,NaN,あめうけざら,59,63,80,65,80,58,405
メガカメックス,9,メガカメックス,みず,NaN,メガランチャー,NaN,NaN,79,103,120,135,115,78,630
キャタピー,10,キャタピー,むし,NaN,りんぷん,NaN,にげあし,45,30,35,20,20,45,195
トランセル,11,トランセル,むし,NaN,だっぴ,NaN,NaN,50,20,55,25,25,30,205
バタフリー,12,バタフリー,むし,ひこう,ふくがん,NaN,いろめがね,60,45,50,90,80,70,395
ビードル,13,ビードル,むし,どく,りんぷん,NaN,にげあし,40,35,30,20,20,50,195
コクーン,14,コクーン,むし,どく,だっぴ,NaN,NaN,45,25,50,25,25,35,205

In [50]:
df

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ブリザポス,896,ブリザポス,こおり,NaN,しろのいななき,NaN,NaN,100,145,130,65,110,30,580
レイスポス,897,レイスポス,ゴースト,NaN,くろのいななき,NaN,NaN,100,65,60,145,80,130,580
バドレックス,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500
バドレックス(はくばじょうのすがた),898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680
バドレックス(こくばじょうのすがた),898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680

In [51]:
df.drop(5)

KeyError: '[5] not found in axis'

In [52]:
df.index[5]

'リザード'

In [53]:
df.drop(df.index[5]).head(15)

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1.0,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45.0,49.0,49.0,65.0,65.0,45.0,318.0
フシギソウ,2.0,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60.0,62.0,63.0,80.0,80.0,60.0,405.0
フシギバナ,3.0,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80.0,82.0,83.0,100.0,100.0,80.0,525.0
メガフシギバナ,3.0,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80.0,100.0,123.0,122.0,120.0,80.0,625.0
ヒトカゲ,4.0,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39.0,52.0,43.0,60.0,50.0,65.0,309.0
リザードン,6.0,リザードン,ほのお,ひこう,もうか,NaN,サンパワー,78.0,84.0,78.0,109.0,85.0,100.0,534.0
メガリザードンX,6.0,メガリザードンX,ほのお,ドラゴン,かたいツメ,NaN,NaN,78.0,130.0,111.0,130.0,85.0,100.0,634.0
メガリザードンY,6.0,メガリザードンY,ほのお,ひこう,ひでり,NaN,NaN,78.0,104.0,78.0,159.0,115.0,100.0,634.0
ゼニガメ,7.0,ゼニガメ,みず,NaN,げきりゅう,NaN,あめうけざら,44.0,48.0,65.0,50.0,64.0,43.0,314.0
カメール,8.0,カメール,みず,NaN,げきりゅう,NaN,あめうけざら,59.0,63.0,80.0,65.0,80.0,58.0,405.0
カメックス,9.0,カメックス,みず,NaN,げきりゅう,NaN,あめうけざら,79.0,83.0,100.0,85.0,105.0,78.0,530.0
メガカメックス,9.0,メガカメックス,みず,NaN,メガランチャー,NaN,NaN,79.0,103.0,120.0,135.0,115.0,78.0,630.0
キャタピー,10.0,キャタピー,むし,NaN,りんぷん,NaN,にげあし,45.0,30.0,35.0,20.0,20.0,45.0,195.0
トランセル,11.0,トランセル,むし,NaN,だっぴ,NaN,NaN,50.0,20.0,55.0,25.0,25.0,30.0,205.0
バタフリー,12.0,バタフリー,むし,ひこう,ふくがん,NaN,いろめがね,60.0,45.0,50.0,90.0,80.0,70.0,395.0

In [57]:
df.index[[0,4,9]]

Index(['フシギダネ', 'ヒトカゲ', 'ゼニガメ'], dtype='object', name='ポケモン名')

In [55]:
df.head(15)

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309
リザード,5,リザード,ほのお,NaN,もうか,NaN,サンパワー,58,64,58,80,65,80,405
リザードン,6,リザードン,ほのお,ひこう,もうか,NaN,サンパワー,78,84,78,109,85,100,534
メガリザードンX,6,メガリザードンX,ほのお,ドラゴン,かたいツメ,NaN,NaN,78,130,111,130,85,100,634
メガリザードンY,6,メガリザードンY,ほのお,ひこう,ひでり,NaN,NaN,78,104,78,159,115,100,634
ゼニガメ,7,ゼニガメ,みず,NaN,げきりゅう,NaN,あめうけざら,44,48,65,50,64,43,314
カメール,8,カメール,みず,NaN,げきりゅう,NaN,あめうけざら,59,63,80,65,80,58,405
カメックス,9,カメックス,みず,NaN,げきりゅう,NaN,あめうけざら,79,83,100,85,105,78,530
メガカメックス,9,メガカメックス,みず,NaN,メガランチャー,NaN,NaN,79,103,120,135,115,78,630
キャタピー,10,キャタピー,むし,NaN,りんぷん,NaN,にげあし,45,30,35,20,20,45,195
トランセル,11,トランセル,むし,NaN,だっぴ,NaN,NaN,50,20,55,25,25,30,205

In [56]:
df.drop(df.index[[0,4,9]]).head(15)

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギソウ,2.0,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60.0,62.0,63.0,80.0,80.0,60.0,405.0
フシギバナ,3.0,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80.0,82.0,83.0,100.0,100.0,80.0,525.0
メガフシギバナ,3.0,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80.0,100.0,123.0,122.0,120.0,80.0,625.0
リザード,5.0,リザード,ほのお,NaN,もうか,NaN,サンパワー,58.0,64.0,58.0,80.0,65.0,80.0,405.0
リザードン,6.0,リザードン,ほのお,ひこう,もうか,NaN,サンパワー,78.0,84.0,78.0,109.0,85.0,100.0,534.0
メガリザードンX,6.0,メガリザードンX,ほのお,ドラゴン,かたいツメ,NaN,NaN,78.0,130.0,111.0,130.0,85.0,100.0,634.0
メガリザードンY,6.0,メガリザードンY,ほのお,ひこう,ひでり,NaN,NaN,78.0,104.0,78.0,159.0,115.0,100.0,634.0
カメール,8.0,カメール,みず,NaN,げきりゅう,NaN,あめうけざら,59.0,63.0,80.0,65.0,80.0,58.0,405.0
カメックス,9.0,カメックス,みず,NaN,げきりゅう,NaN,あめうけざら,79.0,83.0,100.0,85.0,105.0,78.0,530.0
メガカメックス,9.0,メガカメックス,みず,NaN,メガランチャー,NaN,NaN,79.0,103.0,120.0,135.0,115.0,78.0,630.0
キャタピー,10.0,キャタピー,むし,NaN,りんぷん,NaN,にげあし,45.0,30.0,35.0,20.0,20.0,45.0,195.0
トランセル,11.0,トランセル,むし,NaN,だっぴ,NaN,NaN,50.0,20.0,55.0,25.0,25.0,30.0,205.0
バタフリー,12.0,バタフリー,むし,ひこう,ふくがん,NaN,いろめがね,60.0,45.0,50.0,90.0,80.0,70.0,395.0
ビードル,13.0,ビードル,むし,どく,りんぷん,NaN,にげあし,40.0,35.0,30.0,20.0,20.0,50.0,195.0
コクーン,14.0,コクーン,むし,どく,だっぴ,NaN,NaN,45.0,25.0,50.0,25.0,25.0,35.0,205.0

In [23]:
df_num = pd.read_csv("PokemonStatus_Gen8.csv")
df_num.head()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
0,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
1,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
2,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
3,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
4,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309

In [25]:
df_num.drop(0).head()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
1,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
2,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
3,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
4,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309
5,5,リザード,ほのお,NaN,もうか,NaN,サンパワー,58,64,58,80,65,80,405

# 列の削除

In [60]:
df.head()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309

In [58]:
# 行の場合
df.drop("ピカチュウ")
# 列の場合
df.drop('図鑑番号', axis=1).head()

,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,
フシギダネ,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309

### Axis = 軸

axis = 0 → x方向(行)

axis = 1 → y方向(列)

columns = 列

In [61]:
df.head()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
フシギダネ,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309

In [28]:
df.drop(columns='図鑑番号').head()

,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,
フシギダネ,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309

In [30]:
df.drop(['図鑑番号', '夢特性'], axis=1).head()

,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,
フシギダネ,フシギダネ,くさ,どく,しんりょく,NaN,45,49,49,65,65,45,318
フシギソウ,フシギソウ,くさ,どく,しんりょく,NaN,60,62,63,80,80,60,405
フシギバナ,フシギバナ,くさ,どく,しんりょく,NaN,80,82,83,100,100,80,525
メガフシギバナ,メガフシギバナ,くさ,どく,あついしぼう,NaN,80,100,123,122,120,80,625
ヒトカゲ,ヒトカゲ,ほのお,NaN,もうか,NaN,39,52,43,60,50,65,309

In [32]:
df.drop(columns=['図鑑番号', '夢特性']).head()

,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,
フシギダネ,フシギダネ,くさ,どく,しんりょく,NaN,45,49,49,65,65,45,318
フシギソウ,フシギソウ,くさ,どく,しんりょく,NaN,60,62,63,80,80,60,405
フシギバナ,フシギバナ,くさ,どく,しんりょく,NaN,80,82,83,100,100,80,525
メガフシギバナ,メガフシギバナ,くさ,どく,あついしぼう,NaN,80,100,123,122,120,80,625
ヒトカゲ,ヒトカゲ,ほのお,NaN,もうか,NaN,39,52,43,60,50,65,309

In [33]:
df.drop(0, axis=1).head()

KeyError: '[0] not found in axis'

In [62]:
df_num

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
0,1,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
1,2,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
2,3,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
3,3,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
4,4,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,896,ブリザポス,こおり,NaN,しろのいななき,NaN,NaN,100,145,130,65,110,30,580
1035,897,レイスポス,ゴースト,NaN,くろのいななき,NaN,NaN,100,65,60,145,80,130,580
1036,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500
1037,898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680
1038,898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680

In [34]:
df_num.drop(0, axis=1).head()

KeyError: '[0] not found in axis'

In [35]:
df.columns[0]

'図鑑番号'

In [36]:
df.drop(df.columns[0], axis=1).head()

,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,
フシギダネ,フシギダネ,くさ,どく,しんりょく,NaN,ようりょくそ,45,49,49,65,65,45,318
フシギソウ,フシギソウ,くさ,どく,しんりょく,NaN,ようりょくそ,60,62,63,80,80,60,405
フシギバナ,フシギバナ,くさ,どく,しんりょく,NaN,ようりょくそ,80,82,83,100,100,80,525
メガフシギバナ,メガフシギバナ,くさ,どく,あついしぼう,NaN,NaN,80,100,123,122,120,80,625
ヒトカゲ,ヒトカゲ,ほのお,NaN,もうか,NaN,サンパワー,39,52,43,60,50,65,309

In [38]:
df.columns[[0,6]]

Index(['図鑑番号', '夢特性'], dtype='object')

In [40]:
df.drop(df.columns[[0,6]], axis=1).head()

,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,
フシギダネ,フシギダネ,くさ,どく,しんりょく,NaN,45,49,49,65,65,45,318
フシギソウ,フシギソウ,くさ,どく,しんりょく,NaN,60,62,63,80,80,60,405
フシギバナ,フシギバナ,くさ,どく,しんりょく,NaN,80,82,83,100,100,80,525
メガフシギバナ,メガフシギバナ,くさ,どく,あついしぼう,NaN,80,100,123,122,120,80,625
ヒトカゲ,ヒトカゲ,ほのお,NaN,もうか,NaN,39,52,43,60,50,65,309

In [63]:
df.tail()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
ブリザポス,896,ブリザポス,こおり,NaN,しろのいななき,NaN,NaN,100,145,130,65,110,30,580
レイスポス,897,レイスポス,ゴースト,NaN,くろのいななき,NaN,NaN,100,65,60,145,80,130,580
バドレックス,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500
バドレックス(はくばじょうのすがた),898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680
バドレックス(こくばじょうのすがた),898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680

# 行の新規作成

In [64]:
df.loc["ダイキ"]

KeyError: 'ダイキ'

In [65]:
df.loc["ダイキ"] = 0

In [66]:
df.tail()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
レイスポス,897,レイスポス,ゴースト,NaN,くろのいななき,NaN,NaN,100,65,60,145,80,130,580
バドレックス,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500
バドレックス(はくばじょうのすがた),898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680
バドレックス(こくばじょうのすがた),898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680
ダイキ,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [71]:
df.loc["ダイキ2"] = [899,"ダイキ2","ほのお","かくとう","ふくつのこころ","もうか","",120,100,30,15,200,135,550]
df.tail()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計
ポケモン名,,,,,,,,,,,,,,
バドレックス,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500
バドレックス(はくばじょうのすがた),898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680
バドレックス(こくばじょうのすがた),898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680
ダイキ,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ダイキ2,899,ダイキ2,ほのお,かくとう,ふくつのこころ,もうか,,120,100,30,15,200,135,550

In [79]:
df["かしこさ"] = 0
df.tail()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計,かしこさ
ポケモン名,,,,,,,,,,,,,,,
バドレックス,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500,0
バドレックス(はくばじょうのすがた),898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680,0
バドレックス(こくばじょうのすがた),898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680,0
ダイキ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ダイキ2,899,ダイキ2,ほのお,かくとう,ふくつのこころ,もうか,,120,100,30,15,200,135,550,0

In [78]:
daiki2 = pd.DataFrame(df.loc["ダイキ2"]).T
daiki2

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計,かしこさ
ダイキ2,899,ダイキ2,ほのお,かくとう,ふくつのこころ,もうか,,120,100,30,15,200,135,550,0

In [81]:
df.loc["ダイキ2","かしこさ"] = 95

In [82]:
df.tail()

,図鑑番号,ポケモン名,タイプ１,タイプ２,通常特性１,通常特性２,夢特性,HP,こうげき,ぼうぎょ,とくこう,とくぼう,すばやさ,合計,かしこさ
ポケモン名,,,,,,,,,,,,,,,
バドレックス,898,バドレックス,エスパー,くさ,きんちょうかん,NaN,NaN,100,80,80,80,80,80,500,0
バドレックス(はくばじょうのすがた),898,バドレックス(はくばじょうのすがた),エスパー,こおり,じんばいったい,NaN,NaN,100,165,150,85,130,50,680,0
バドレックス(こくばじょうのすがた),898,バドレックス(こくばじょうのすがた),エスパー,ゴースト,じんばいったい,NaN,NaN,100,85,80,165,100,150,680,0
ダイキ,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
ダイキ2,899,ダイキ2,ほのお,かくとう,ふくつのこころ,もうか,,120,100,30,15,200,135,550,95

# 条件分岐

if 条件式1:

    `条件式1がTrueのときに行う処理`

if x=0:

    aaaaaa
    aaaaa
    aaaaaaaaaa
    aaaaaaaaaaa
    
sample

aaaaaa

aaaaaaa

aaaaaaaa

# 入力した数字が偶数かどうか判定するプログラム

In [1]:
x = 2917323719
###
#if 偶数だったら:
#    print("偶数だよ！！")
#else 偶数じゃなかったら:
#    print("奇数だよ！！")
###

### 整数が偶数である　＝　2で割り切れる
### つまり2で割った余りが0

Pythonで`%`はあまりを求める

In [2]:
100 % 3

1

In [3]:
100 % 2

0

In [4]:
if x % 2 == 0:
    print("偶数だよ！！")
#else 偶数じゃなかったら:
#    print("奇数だよ！！")

### 等しいかどうかの判定 ==

In [5]:
x = 2917323719


if x % 2 == 0:
    print("偶数だよ！！")
elif x % 2 == 1:
    print("奇数だよ！！")

奇数だよ！！

In [6]:
x = 2917323719

if x % 2 == 0:
    print("偶数だよ！！")
else:
    print("奇数だよ！！")

奇数だよ！！

In [7]:
#for aaa in aaa:

#    aaa

In [8]:
array = []
array = range(10)

[0,1,2,3,4,5,6,7,8,9]

# 10回繰り返したいとき　→　range(10)


range(繰り返したい回数)

In [9]:
x = 0
for y in range(10):
    x += 1
    print(x)

1
2
3
4
5
6
7
8
9
10